version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env

  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/index
    depends_on:
      - db
